###
POST http://localhost:3000/actor
content-type: application/json

{
    "first_name": "admin",
    "last_name": "demo"
}

###
POST http://localhost:3000/actor
content-type: application/json

{
    "first_name": "@@@@@@",
    "last_name": "111111"
}

###
GET http://localhost:3000/actor/999999

###
GET http://localhost:3000/actor/202

###
GET http://localhost:3000/actor/hcmus


###
PATCH  http://localhost:3000/actor/220
content-type: application/json

{
    "first_name": "HCMUS",
    "last_name": "EDU"
}


###
DELETE  http://localhost:3000/actor/218
